### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by isackj07** [NullCode1337/NullRAT#25]
is there supposed to be rat.exe after running compiler? bc after running compiler nothing changes

**Comment by NullCode1337** [comment]
did you run the dependencies installer
also make sure the pip folder is on path

**Comment by isackj07** [comment]
![image](https://user-images.githubusercontent.com/95695326/158999169-f958242e-16a6-4441-99f2-a4ab69ff17b5.png)
this is what it keeps giving me after running the compiler

**Comment by usrDottik** [comment]
Reboot the cmd if you just ran the dependency installer, and try again, if it repeats, try executing `pyarmor` if it gives Unknown Command or such, check If your Python installation is working correctly or if the python modules folder is in PATH

**Comment by isackj07** [comment]
![image](https://user-images.githubusercontent.com/95695326/159103950-0b795106-f521-43bc-8a48-e4bd56f6bf6c.png)
Ran the dependency installer and no errors with the dependencies and pyarmor won't execute even when the module folder is in PATH

**Comment by NullCode1337** [comment]
can you show me what module folder is in path? and also it's contents

**Comment by isackj07** [comment]
![image](https://user-images.githubusercontent.com/95695326/159108917-8b121149-ef99-4f31-83c7-eb1db992075e.png)
highlighted path is pyarmor

![image](https://user-images.githubusercontent.com/95695326/159108829-a0d944be-6256-4ff8-b130-092d7715687c.png)

**Comment by NullCode1337** [comment]
jesus. btw, you only need the "Scripts" folder in path
everything else might just cause trouble...

**Comment by NullCode1337** [comment]
can you show me the scripts folder btw

**Comment by isackj07** [comment]
Scripts
![image](https://user-images.githubusercontent.com/95695326/159129160-fcaafc83-155b-4483-9d87-e4dbad7840f4.png)

Nullrat folder
![image](https://user-images.githubusercontent.com/95695326/159129280-63636825-6e71-4d57-bdcc-72ad2438e089.png)

**Comment by usrDottik** [comment]
@isackj07 You have your PATH setted up the incorrect way, `pyarmor` won't be executed, add the following PATH (I made it based on the screenshots you sent) `C:\Users\Isac\AppData\Roaming\Python\Python310\Scripts`, Just add it, and attempt to use the compiler again

**Comment by isackj07** [comment]
Tysm man, it compiled successfully but when I opened RAT.exe nothing happened
![image](https://user-images.githubusercontent.com/95695326/159147905-386bc789-76a9-40e3-8796-27068340e73d.png)

![image](https://user-images.githubusercontent.com/95695326/159147857-73f94348-64a0-4e8f-beec-56586d84a2d4.png)
it just runs in the background and nothing happens in the discord either

**Comment by usrDottik** [comment]
Ok, the compile error seems to be caused because in the dependency installer I call `pip` using the `--user` argument, so it installs the packages there, instead that in the default location, I should add an option for that next time. Regarding the RAT not behaving as expected, @NullCode1337

**Comment by NullCode1337** [comment]
sorry for dying
@isackj07 it can happen because of improper notification/guild variables

eitther that or you didn't invite the bot with the proper scopes. i mentioned it twice in the readme

**Comment by NullCode1337** [comment]
ayo?
I'm gonna close issue if it's gonna be dead, if you have any further problems feel free to re-comment
