### ISSUE TITLE
Failed to exec RAT.exe, No Module named Disnake

### ISSUE THREAD

**Issue by SlepPoweredBy2** [NullCode1337/NullRAT#49]
When I attempt to execute RAT.exe (the compiled version of my RAT) then it shows this.

![image](https://user-images.githubusercontent.com/113756956/196051930-5abff5b2-1c46-449e-a43f-1e3a65b28a05.png)

**Comment by StuKit** [comment]
"pip install disnake" maybe ?

**Comment by SlepPoweredBy2** [comment]
I did, same error.

**Comment by NullCode1337** [comment]
> When I attempt to execute RAT.exe (the compiled version of my RAT) then it shows this.
> 
> ![image](https://user-images.githubusercontent.com/113756956/196051930-5abff5b2-1c46-449e-a43f-1e3a65b28a05.png)

have you installed python properly?
don't use microsoft store version of python, when installing python choose "Add to path" and "Install for all users"

**Comment by SlepPoweredBy2** [comment]
nah bro i installed python correctly no microsoft store shit idk bro it wont show the modules it like ignores them
